USING KNN ALGORITHM

In [113]:
import numpy as mp
import pandas as pd

In [114]:
data=pd.read_csv('/content/Social_Network_Ads.csv')

In [115]:
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [116]:
df=data.drop(['User ID'],axis=1)

In [117]:
df.head()

Gender  Age  EstimatedSalary  Purchased
0    Male   19            19000          0
1    Male   35            20000          0
2  Female   26            43000          0
3  Female   27            57000          0
4    Male   19            76000          0

In [118]:
#ONE HOT CODING
df['Gender']=df['Gender'].apply({'Male':0,'Female':1}.get)

In [119]:
x=df[['Gender','Age','EstimatedSalary']]
y=df['Purchased']

In [120]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8)

In [163]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5)

In [164]:
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [165]:
y_pred=knn.predict(x_test)

In [166]:
y_pred

array([1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [167]:
#Calculating Accuracy for Model
from sklearn.metrics import accuracy_score , confusion_matrix
cm=confusion_matrix(y_test,y_pred)
ac=accuracy_score(y_test,y_pred) 

In [168]:
print(cm)

[[47  7]
 [ 8 18]]


In [169]:
print(ac)

0.8125


In [128]:
#Adding New Entry
new_data={'Gender':0,'Age':32,'EstimatedSalary':10000}

In [129]:
print(new_data)

{'Gender': 0, 'Age': 32, 'EstimatedSalary': 10000}


In [130]:
index=[1]
my_data=pd.DataFrame(new_data,index)

In [131]:
print(my_data)

   Gender  Age  EstimatedSalary
1       0   32            10000


In [132]:
y_pred=knn.predict(my_data)

In [133]:
print('The Person Will Do Shopping if it is 1 and wont do shopping is 0',y_pred)

The Person Will Do Shopping if it is 1 and wont do shopping is 0 [0]


USING LOGISTIC REGRESSION

In [134]:
from sklearn.linear_model import LogisticRegression
log_model=LogisticRegression()

In [135]:
log_model.fit(x_train,y_train)

LogisticRegression()

In [136]:
y_pred=log_model.predict(x_test)

In [137]:
from sklearn.metrics import accuracy_score,confusion_matrix
cm=confusion_matrix(y_test,y_pred)
ac=accuracy_score(y_test,y_pred)

In [138]:
print(cm)

[[54  0]
 [26  0]]


In [139]:
print(ac)

0.675


USING DECISION TREE ALGORITHM

In [140]:
from sklearn.tree import DecisionTreeClassifier
tree_classifier=DecisionTreeClassifier()

In [143]:
tree_classifier.fit(x_train,y_train)

DecisionTreeClassifier()

In [144]:
t_pred=tree_classifier.predict(x_test)

In [157]:
from sklearn.metrics import accuracy_score, confusion_matrix
cm=confusion_matrix(y_test,t_pred)
ac=accuracy_score(y_test,t_pred)

In [158]:
print(cm)

[[49  5]
 [ 8 18]]


In [159]:
print(ac)

0.8375


Using Random Forest ALGORITHM

In [153]:
from sklearn.ensemble import RandomForestClassifier
forest_classifier=RandomForestClassifier()

In [154]:
forest_classifier.fit(x_train,y_train)

RandomForestClassifier()

In [155]:
r_pred=forest_classifier.predict(x_test)

In [160]:
from sklearn.metrics import accuracy_score, confusion_matrix
cm=confusion_matrix(y_test,r_pred)
ac=accuracy_score(y_test,r_pred)

In [161]:
print(cm)

[[51  3]
 [ 6 20]]


In [162]:
print(ac)

0.8875
